### ISSUE TITLE
Fix so it doesn't output PASS in the console

### ISSUE THREAD

**Issue by g33kidd** [Meoowww/Crirc#8]
If this is possible to disable as of now, please do let me know. Kind of annoying thing to have. If not, I'll dig through and make a PR :)

**Comment by Nephos** [comment]
You're right!
We didn't manage to do it but I could do it in a few minutes.

**Comment by Nephos** [comment]
b6742edf45733ad4fe0ba9fa774799094c1ac8e3 fix the PASS output.

When the password is sent, the command is replaced with `PASS ****`.
It's on master.
